services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DB_NAME:-socium-code}-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - minio
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: ${DB_NAME:-socium-code}-postgres-prod
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-socium-code}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: ${DB_NAME:-socium-code}-minio-prod
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data_prod:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data_prod:
  minio_data_prod: